config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: { registrations: "registrations"}

  get '/customers/:id' => "customers#show"



  get 'pages/show'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/pages/:permalink' => "pages#permalink"

  scope "/checkout/" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "orders#create", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end

  get "/checkout/success", redirect("/")


  authenticate :customer do
  resources :cart, only: %i[index]
  end
  resources :cart, only: %i[create destroy]
  resources :orders, only: %i[index create destroy show]
  resources :years, only: %i[index show]
  resources :authors, only: %i[index show]
  resources :genres, only: %i[index show]
  resources :books, only: %i[index show search] do
    collection do
      get "search"
      get "new"
      get "sale"
    end
  end

  root "home#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  has_many :genres, through: :books

  validates :name, presence: true

    def self.ordered_by_books
    self.select("authors.*")
        .select("COUNT(authors.id) as book_count")
        .left_joins(:books)
        .group("authors.id")
        .order("book_count DESC")
    end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author

  has_many :book_genres
  has_many :genres, through: :book_genres
  accepts_nested_attributes_for :book_genres, allow_destroy: true

  has_many :orderbooks
  has_many :orders, through: :orderbooks

  has_one_attached :image

  validates :title, :isbn, presence: true
  validates :price, presence: true, numericality: true
  validates :rating, presence: true, numericality: true

  def genres_list
    genres.map(&:name).join(", ")
    genres.map { |genre| genre.name }.join(", ")
  end
end

app/models/book_genre.rb
class BookGenre < ApplicationRecord
  belongs_to :book
  belongs_to :genre
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :province
  has_many :orders
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :book_genres
  has_many :books, through: :book_genres

  has_many :authors, through: :books

  def genre_name
    return self.name
  end
end

app/models/order.rb
class Order < ApplicationRecord
  before_create :set_subtotal, :set_order_gst, :set_order_pst, :set_order_hst, :set_total
  has_many :orderbooks
  has_many :books, through: :orderbooks

  belongs_to :customer
  has_many :provinces, through: :customers

  def subtotal
    orderbooks.collect{|orderbook| orderbook.valid? ? orderbook.order_price*orderbook.quantity : 0}.sum
  end

  def total
    orderbooks.collect{|orderbook| orderbook.valid? ? orderbook.order_price*orderbook.quantity : 0}.sum + (order_gst + order_pst + order_hst)
  end

  def get_province
    customer = Customer.find_by(id: customer_id)
    province = Province.find_by(id: customer.province_id)
  end

  def order_gst
    subtotal * (get_province.gst)
  end

  def order_pst
    subtotal * (get_province.pst)
  end

  def order_hst
    subtotal * (get_province.hst)
  end

  def set_subtotal
    self[:subtotal] = subtotal
  end

  def set_order_gst
    self[:gst] = order_gst
  end

  def set_order_pst
    self[:pst] = order_pst
  end

  def set_order_hst
    self[:hst] = order_hst
  end

  def set_total
    self[:total] = total
  end
end

app/models/orderbook.rb
class Orderbook < ApplicationRecord
  belongs_to :order
  belongs_to :book


  def current_price
    if persisted?
      self[:order_price]
    else
      book.price
    end
  end

  def total
    order_price * quantity
  end

  def set_order_price
    self[:order_price] = order_price
  end

  def set_total
    self[:total] = total * quantity
  end

end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers
  has_many :orders, :through => :customers
end

app/models/year.rb
class Year < ApplicationRecord
  belongs_to :books

  def self.ordered_by_books
    self.select("years.*")
        .select("COUNT(years.id) as book_count")
        .left_joins(:books)
        .group("years.id")
        .order("book_count DESC")
    end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index

  add_breadcrumbs("Shopping Cart")
  end

  def create
    #add params[:id]
    #logger.debug(params[:id])
    id = params[:id].to_i
    book = Book.find(id)
    session[:shopping_cart].has_key?(id.to_s) ? hash = {id => session[:shopping_cart][id.to_s] += 1} : hash = {id => 1}
    session[:shopping_cart].merge!(hash)
    flash[:notice] = "#{book.title} was added to the cart"
    redirect_back(fallback_location: root_path)
  end

  def destroy
    id = params[:id].to_i
    book = Book.find(id)
    session[:shopping_cart].has_key?(id.to_s) ? session[:shopping_cart][id.to_s] > 0 ? session[:shopping_cart][id.to_s] -= 1 : "" : ""
    session[:shopping_cart].has_key?(id.to_s) ? session[:shopping_cart][id.to_s] == 0 ? session[:shopping_cart].delete(id.to_s) : "" : ""
    flash[:notice] = "#{book.title} was removed from the cart"
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/cart/create.html.erb
<h1>Cart#create</h1>
<p>Find me in app/views/cart/create.html.erb</p>

app/views/cart/destroy.html.erb
<h1>Cart#destroy</h1>
<p>Find me in app/views/cart/destroy.html.erb</p>

app/views/cart/index.html.erb
<div class="column pt-5">
<div class="card mb-5 px-5 pt-5">
<% subtotal ||= 0 %>
    <% session[:shopping_cart].each do |id, item| %>
      <% qty = session[:shopping_cart][id] %>
      <% book = Book.find(id) %>
      <% cost = 0%>
<% if book.on_sale %>
<% cost = book.sale_price%>
<% else %>
<% cost = book.price %>
<% end %>
<div class="card-content column mb-2">
  <div class="">
    <div class="media">
      <div class="media-left">
        <figure class="image is-48x48">
          <img src="<%= book.cover_art %>" />
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-4">
            <%= link_to book.title, book %>
        </p>
        <p class="subtitle is-6 mb-1"><%= link_to book.author.name, book.author %></p>
        <p class="subtitle is-7">ISBN: <%= book.isbn %></p>
      </div>
      <div class="pl-3 column is-one-fifth">
        <p class="has-text-right">Quantity: <%= qty %></p>
        <p class="has-text-right">Price: <%= number_to_currency(cost)%>
        <p class="has-text-right"> Subtotal: <%= number_to_currency(cost * qty) %></p>
      <div><% subtotal += cost * qty %>
      <div class="columns level-right mt-2 mr-4">
      <% if session[:shopping_cart][book.id.to_s] %>
        <%= form_with url: cart_path(book), method: :delete do %>
          <%= button_tag '-', {class: "button card-footer-item is-size-6 add-to-cart mx-4"} %>
        <% end %>

        <%= form_with url: cart_index_path do %>
          <%= hidden_field_tag(:id, book.id) %>
          <div class="mx-1">
          <%= button_tag '+', {class: "mx-4 button card-footer-item is-size-6 add-to-cart"} %>
          </div>
        <% end %>

        <%= form_with url: cart_path(book), method: :delete do %>
          <%= button_tag 'x', {class: "mx-4 button card-footer-item is-size-6 add-to-cart"} %>
        <% end %>
      <% end %>
      </div>
      </div>
    </div>

      </div>
      </div>
      </div>
      <% end %>

    <% if customer_signed_in? %>
    <div class="mt-5 title is-5 red-text has-text-right mb-0 pr-5">Subtotal: <%= number_to_currency(subtotal) %></div>
    <% if current_customer.province.gst > 0%>
    <div class="mt-2 has-text-right mb-0 pr-5">GST: <%= number_to_currency(subtotal * current_customer.province.gst) %></div>
    <% end %>
    <% if current_customer.province.pst > 0%>
    <div class="mt-2 has-text-right mb-0 pr-5">PST: <%= number_to_currency(subtotal * current_customer.province.pst) %></div>
    <% end %>
    <% if current_customer.province.hst > 0%>
    <div class="mt-2 has-text-right mb-0 pr-5">HST: <%= number_to_currency(subtotal * current_customer.province.hst) %></div>
    <% end %>
    <% @total = (subtotal * (1 + current_customer.province.gst + current_customer.province.pst + current_customer.province.hst)) %>
    <div class="mt-2 title is-2 red-text has-text-right mb-5 pr-5 pb-5">Total: <%= @total > 0 ? @total = number_to_currency(@total-0.01) : number_to_currency(@total) %>
    <%end%>
    <div class="pt-5 level-right has-text-center is-full">
    <% if session['shopping_cart'].count > 0%>

    <%= form_with url: checkout_create_path, remote: true do %>
      <%= hidden_field_tag(:cart, session['shopping_cart'], autocomplete: "off")%>
      <%= button_tag 'Buy Now!', {class: "button is-primary is-large"} %>
    <% end %>

    <% end %>
    </div>

    </div>




    </div>