config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: { registrations: "registrations"}

  get '/customers/:id' => "customers#show"



  get 'pages/show'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/pages/:permalink' => "pages#permalink"

  scope "/checkout/" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "orders#create", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end

  get "/checkout/success", redirect("/")


  authenticate :customer do
  resources :cart, only: %i[index]
  end
  resources :cart, only: %i[create destroy]
  resources :orders, only: %i[index create destroy show]
  resources :years, only: %i[index show]
  resources :authors, only: %i[index show]
  resources :genres, only: %i[index show]
  resources :books, only: %i[index show search] do
    collection do
      get "search"
      get "new"
      get "sale"
    end
  end

  root "home#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  has_many :genres, through: :books

  validates :name, presence: true

    def self.ordered_by_books
    self.select("authors.*")
        .select("COUNT(authors.id) as book_count")
        .left_joins(:books)
        .group("authors.id")
        .order("book_count DESC")
    end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author

  has_many :book_genres
  has_many :genres, through: :book_genres
  accepts_nested_attributes_for :book_genres, allow_destroy: true

  has_many :orderbooks
  has_many :orders, through: :orderbooks

  has_one_attached :image

  validates :title, :isbn, presence: true
  validates :price, presence: true, numericality: true
  validates :rating, presence: true, numericality: true

  def genres_list
    genres.map(&:name).join(", ")
    genres.map { |genre| genre.name }.join(", ")
  end
end

app/models/book_genre.rb
class BookGenre < ApplicationRecord
  belongs_to :book
  belongs_to :genre
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :province
  has_many :orders
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :book_genres
  has_many :books, through: :book_genres

  has_many :authors, through: :books

  def genre_name
    return self.name
  end
end

app/models/order.rb
class Order < ApplicationRecord
  before_create :set_subtotal, :set_order_gst, :set_order_pst, :set_order_hst, :set_total
  has_many :orderbooks
  has_many :books, through: :orderbooks

  belongs_to :customer
  has_many :provinces, through: :customers

  def subtotal
    orderbooks.collect{|orderbook| orderbook.valid? ? orderbook.order_price*orderbook.quantity : 0}.sum
  end

  def total
    orderbooks.collect{|orderbook| orderbook.valid? ? orderbook.order_price*orderbook.quantity : 0}.sum + (order_gst + order_pst + order_hst)
  end

  def get_province
    customer = Customer.find_by(id: customer_id)
    province = Province.find_by(id: customer.province_id)
  end

  def order_gst
    subtotal * (get_province.gst)
  end

  def order_pst
    subtotal * (get_province.pst)
  end

  def order_hst
    subtotal * (get_province.hst)
  end

  def set_subtotal
    self[:subtotal] = subtotal
  end

  def set_order_gst
    self[:gst] = order_gst
  end

  def set_order_pst
    self[:pst] = order_pst
  end

  def set_order_hst
    self[:hst] = order_hst
  end

  def set_total
    self[:total] = total
  end
end

app/models/orderbook.rb
class Orderbook < ApplicationRecord
  belongs_to :order
  belongs_to :book


  def current_price
    if persisted?
      self[:order_price]
    else
      book.price
    end
  end

  def total
    order_price * quantity
  end

  def set_order_price
    self[:order_price] = order_price
  end

  def set_total
    self[:total] = total * quantity
  end

end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers
  has_many :orders, :through => :customers
end

app/models/year.rb
class Year < ApplicationRecord
  belongs_to :books

  def self.ordered_by_books
    self.select("years.*")
        .select("COUNT(years.id) as book_count")
        .left_joins(:books)
        .group("years.id")
        .order("book_count DESC")
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/layouts/_breadcrumb.html.erb
<nav class="breadcrumb has-succeeds-separator pt-5" aria-label="breadcrumbs">
  <ul>
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <% @breadcrumbs.each do |breadcrumb| %>
      <% if breadcrumb[:path].nil?%>
        <li class="breadcrumb-item active" aria-current="page">
          <%= breadcrumb[:label] %>
        </li>
      <% else %>
        <li class="breadcrumb-item">
          <%= link_to breadcrumb[:label], breadcrumb[:path] %>
        </li>
      <% end %>
    <% end %>
  </ul>
</nav>

app/views/layouts/_footer.html.erb
<footer class="has-background-black has-text-centered">
  <div class="mt-2 mb-3 is-size-6">
    <%= link_to 'About Us', "/pages/about_us" %> || <%= link_to 'Contact Us', "/pages/contact_us" %>
  </div>
  <div class="mb-2 is-size-7">
    <strong>Turn the Page eCommerce Platform</strong>
      by <a href="">Chantal Wiebe</a> || Made using <a href="">Ruby on Rails.</a>
  </div>
</footer>

app/views/layouts/_header.html.erb
<% @genres = Genre.all %>
<nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="/">
            <%= image_tag ("TTP-Logo.png")%>
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <a href="/books" class="navbar-item">
                Books
            </a>

            <a href="/authors" class="navbar-item">
                Authors
            </a>

            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                    Genres
                </a>

                <div class="navbar-dropdown">
                    <% @genres.each do |g| %>
                    <a class="navbar-item" href="/genres/<%= g.id %>">
                        <%= g.name %>
                    </a>
                    <% end %>
                </div>
            </div>
        </div>
        <% names = [] %>
        <% @genres.each do |g| %>
        <% names.push g.name %>
        <% end %>
        <div class="navbar-end">
            <div class="navbar-item">
                <%= form_with(url: search_books_path, method: :get, local: true) do |f| %>
                <div class="field">
                    <div class="columns is-gapless">
                        <div class="column is-half"><%= text_field_tag(:keywords, nil, class: "input", placeholder: "Search for Books") %></div>
                        <div class="select"><%= f.select :category, options_for_select(names, params[:category]), { include_blank: 'Genres'} %></div>
                        <div class="column"><%= submit_tag("🔎", class: "button is-primary") %></div>
                    </div>
                </div>
                <% end %>
                <% if session['shopping_cart'] == {} %>
                <a class="button is-primary" href="/cart">
                <% else %>
                <a class="button is-info" href="/cart">
                <% end %>
                <% if session['shopping_cart'].count > 0%>
                <%= session['shopping_cart'].count %>
                <% end %>
                    🛒
                </a>
                <% if customer_signed_in? %>
                <p>Hello, <%= link_to current_customer.first_name, "/customers/#{current_customer.id}" %> - <%= link_to "Sign out", destroy_customer_session_path, :method => 'delete' %></p>
                <% else %>
                <a class="button is-primary" href="/customers/sign_in">
                Sign in
                </a>
                <% end %>
            </div>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewEcommerceProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container-padding">
    <%= render 'layouts/breadcrumb'%>
    <% if flash[:notice] %>
      <p><%= flash[:notice] %></p>
    <% end %>
    <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>